version: '3.8'

services:
  latex_editor:
    build: .
    container_name: latex_editor_container
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: ["python", "app.py"]